name: Feature Request
description: Propose a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion. Please describe the feature you'd like to see.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? Is it related to a frustration?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, examples, or references.
    validations:
      required: false
